sudo: required
services:
  - docker

before_install:
  - docker build -t suveenkumarchowdary/docker-react -f Dockerfile.dev .

script:
  - docker run suveenkumarchowdary/docker-react yarn test --coverage